// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRPqYcQ0Ahy-1DykNu-C1mwBz2b3oAd4s',
    appId: '1:130185560048:web:0db8fd1198d6ab4746e735',
    messagingSenderId: '130185560048',
    projectId: 'chatly-app-e00bb',
    authDomain: 'chatly-app-e00bb.firebaseapp.com',
    storageBucket: 'chatly-app-e00bb.appspot.com',
    measurementId: 'G-YZCQ65BZPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD36tprJZPBj_i_71yjXIdsvwaMiu49O0o',
    appId: '1:130185560048:android:61ecdf330abe8f2e46e735',
    messagingSenderId: '130185560048',
    projectId: 'chatly-app-e00bb',
    storageBucket: 'chatly-app-e00bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjCyIqad3tBSLKiZaxkzcNk9TdPV4A-eU',
    appId: '1:130185560048:ios:1d3867dde1450c8d46e735',
    messagingSenderId: '130185560048',
    projectId: 'chatly-app-e00bb',
    storageBucket: 'chatly-app-e00bb.appspot.com',
    iosBundleId: 'com.example.chatlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjCyIqad3tBSLKiZaxkzcNk9TdPV4A-eU',
    appId: '1:130185560048:ios:1d3867dde1450c8d46e735',
    messagingSenderId: '130185560048',
    projectId: 'chatly-app-e00bb',
    storageBucket: 'chatly-app-e00bb.appspot.com',
    iosBundleId: 'com.example.chatlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRPqYcQ0Ahy-1DykNu-C1mwBz2b3oAd4s',
    appId: '1:130185560048:web:5944f4231cce4f9246e735',
    messagingSenderId: '130185560048',
    projectId: 'chatly-app-e00bb',
    authDomain: 'chatly-app-e00bb.firebaseapp.com',
    storageBucket: 'chatly-app-e00bb.appspot.com',
    measurementId: 'G-6510QX4M3V',
  );
}
